### ISSUE TITLE
[BUG]: launcher on linux

### ISSUE THREAD

**Issue by B-Nerd** [stephini/SMAS_Launcher#21]
### Describe the Bug

i tried to launch the linux launcher but i got this error 
pygame 2.4.0 (SDL 2.26.4, Python 3.11.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
making dir /home/bnerd/.local/share/SMAS Launcher/source/smw
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 467, in _make_request
  File "urllib3/connectionpool.py", line 1092, in _validate_conn
  File "urllib3/connection.py", line 635, in connect
  File "urllib3/connection.py", line 776, in _ssl_wrap_socket_and_match_hostname
  File "urllib3/util/ssl_.py", line 466, in ssl_wrap_socket
  File "urllib3/util/ssl_.py", line 510, in _ssl_wrap_socket_impl
  File "ssl.py", line 517, in wrap_socket
  File "ssl.py", line 1075, in _create
  File "ssl.py", line 1346, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 790, in urlopen
  File "urllib3/connectionpool.py", line 491, in _make_request
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "launcher.pyw", line 738, in <module>
  File "launcher.pyw", line 730, in main
  File "launcher.pyw", line 533, in build_game
  File "launcher.pyw", line 451, in git_clone
  File "dulwich/client.py", line 781, in fetch
  File "dulwich/client.py", line 2084, in fetch_pack
  File "dulwich/client.py", line 1940, in _discover_references
  File "dulwich/client.py", line 2208, in _http_request
  File "urllib3/_request_methods.py", line 110, in request
  File "urllib3/_request_methods.py", line 143, in request_encode_url
  File "urllib3/poolmanager.py", line 443, in urlopen
  File "urllib3/connectionpool.py", line 874, in urlopen
  File "urllib3/connectionpool.py", line 874, in urlopen
  File "urllib3/connectionpool.py", line 874, in urlopen
  File "urllib3/connectionpool.py", line 844, in urlopen
  File "urllib3/util/retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /snesrev/smw.git/info/refs?service=git-upload-pack (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')))
[21035] Failed to execute script 'launcher' due to unhandled exception!
distro endeavouros kde

### Reproduction Steps

just double clcik it when you don't have a smas launcher in .local

### Expected Behavior

it just works

### Actual Behavior

it did not work

### Operating System

Windows 10 (64bit)

### Screenshots

![Screenshot_20230623_005957](https://github.com/stephini/SMAS_Launcher/assets/65131530/f9309780-9b07-4552-be2d-316aab259ce1)

**Comment by B-Nerd** [comment]
Endeavouros_Cassini_Nova-03-2023_R2 version of eos
