### ISSUE TITLE
[BUG]: launcher crashes

### ISSUE THREAD

**Issue by B-Nerd** [stephini/SMAS_Launcher#28]
### Describe the Bug

when i click on game options & then graphics it crashes

### Reproduction Steps

build it  from source & start the launcher

### Expected Behavior

that option does not crash the launcher

### Actual Behavior

it crashes with this error
Traceback (most recent call last):
  File "/home/bnerd/Games/SMAS_Launcher/launcher.pyw", line 2099, in <module>
    main()
  File "/home/bnerd/Games/SMAS_Launcher/launcher.pyw", line 2096, in main
    create_launcher_window()
  File "/home/bnerd/Games/SMAS_Launcher/launcher.pyw", line 1984, in create_launcher_window
    create_main_window_button(main_window, "Game Options", 100, width//2, 593, show_options_window)#Game Options Button
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bnerd/Games/SMAS_Launcher/launcher.pyw", line 2021, in create_main_window_button
    func()
  File "/home/bnerd/Games/SMAS_Launcher/launcher.pyw", line 677, in show_options_window
    Goptions_window.blit(ButtonG, (87 + calculate_slider_position(0, max(len(shaders)-1, 0), shaderindex), 67 + 41 * 11))
                                                                         ^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()

### Operating System

Linux

### If Linux - Specify Distro And Distro Landmark

EndeavourOS/Arch Cassin Nova-03-2023_R2

### Screenshots

to fix it uncomment this line in the smw.ini
shader = None

**Comment by DaBanana64** [comment]
Same thing happens for me except it won't boot up the launcher
