### ISSUE TITLE
[BUG]: Launcher boots with only error message at splash

### ISSUE THREAD

**Issue by GoldyFredy9** [stephini/SMAS_Launcher#31]
### Describe the Bug

Launcher refuses to start up when proceeding with steps to start the exe file.

### Reproduction Steps

Cloning SMAS.sfc and SMW.sfc in the same directory and booting the launcher as told.

### Expected Behavior

Launcher should begin to show the splash screen and proceed with the game.

### Actual Behavior

Launcher shows up with 1 of 2 errors when booting. second screenshot seems to be looking for a file (presumably a ZSNES savestate judging from the zst extension?)

### Operating System

Windows 11

### Screenshots

![image](https://github.com/stephini/SMAS_Launcher/assets/109116387/c534ec34-07d4-4393-8946-30e40f62525c)

![image](https://github.com/stephini/SMAS_Launcher/assets/109116387/e290536c-d930-4e11-90bb-9c376298b50b)

**Comment by XNINEZERO** [comment]
second this. I have gotten both of these errors.

**Comment by gex581990** [comment]
also getting this error

**Comment by RoyalGuard1991** [comment]
Same issue here.

**Comment by jvne2134** [comment]
i am also getting the same error

**Comment by guslanzetta1** [comment]
Same:

Traceback (most recent call last):
  File "launcher.pyw", line 2099, in <module>
  File "launcher.pyw", line 2091, in main
  File "launcher.pyw", line 1393, in build_game
  File "launcher.pyw", line 1224, in extract_smas
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\gus\\AppData\\Roaming\\SMAS Launcher\\smb1.zst'

**Comment by drencoss** [comment]
I am getting this error when trying to launch the launcher aswell:

Traceback (most recent call last):
  File "launcher.pyw", line 2099, in <module>
  File "launcher.pyw", line 2091, in main
  File "launcher.pyw", line 1393, in build_game
  File "launcher.pyw", line 1224, in extract_smas
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Dav\\AppData\\Roaming\\SMAS Launcher\\smb1.zst'

**Comment by AmberCyprian** [comment]
Also getting the same error under the same conditions. I'm on Windows 11 like the original poster.

Traceback (most recent call last):
  File "launcher.pyw", line 2099, in <module>
  File "launcher.pyw", line 2091, in main
  File "launcher.pyw", line 1393, in build_game
  File "launcher.pyw", line 1224, in extract_smas
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Amber\\AppData\\Roaming\\SMAS Launcher\\smb1.zst'

**Comment by jackrabbit72380** [comment]
having same issue
